# Generated by Django 5.2.17 on 2026-09-27 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=300)),
                ('website_url', models.URLField(blank=True)),
                ('size', models.CharField(choices=[('unknown', 'Unknown'), ('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501+', '501+ employees')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('not_contacted', 'Not contacted'), ('contacted', 'Contacted')], default='not_contacted', max_length=20)),
                ('last_contacted_on', models.DateField(blank=True, null=True)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=300)),
                ('linkedin_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('not_contacted', 'Not contacted'), ('contacted', 'Contacted')], default='not_contacted', max_length=20)),
                ('last_contacted_on', models.DateField(blank=True, null=True)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='applications.company')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
