# Generated by Django 5.2.17 on 2026-09-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_company_companycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
