# Generated by Django 5.2.17 on 2026-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_company_category_company_email_company_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
