# Generated by Django 5.2.17 on 2026-09-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_company_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
